kube_version: v1.17.4
token: b0f7b8.8d1767876297d85c
service_cidr: "10.96.0.0/12"
pod_network_cidr: "10.244.0.0/16"
systemd_dir: /lib/systemd/system
system_env_dir: /etc/sysconfig
network_dir: /etc/kubernetes/network
kubeadmin_config: /etc/kubernetes/admin.conf
kube_addon_dir: /etc/kubernetes/addon
kubeadm_opts: ''
init_opts: ''


# Additional feature to install
additional_features:
  helm: false
  metallb: false
  healthcheck: false

master_ip: "{{ hostvars[groups.k8s_masters | sort | first].ansible_default_ipv4.address }}"
