---
- name: Raspberry Kernel Upgrade
  block:
  - name: Run raspberry kernel upgrade (this can take up to 10 minutes)
    command: /usr/bin/rpi-update
    environment:
      SKIP_WARNING: 1
  - name: Unconditionally reboot the machine with all defaults
    reboot:
  become: yes
  tags: raspberry-upgrade-kernel
