---
- hosts: all
  roles:
    - common
  tags: common

- hosts: raspbian
  roles:
    - common/raspberry
  tags: raspberry-common
  become: yes

- hosts: all
  become: true
  roles:
    - common/docker
  tags: docker

- hosts: k8s_masters
  roles:
    - kubernetes/kubernetes-administration/helm
    - kubernetes/kubernetes-administration/kubetail
#    - kubernetes/kubernetes-administration/kui
  tags: kubernetes-administration

- hosts: k8s_clusters
  roles:
    - kubernetes/kubernetes-reset
  tags: kubernetes-reset

- hosts: k8s_clusters
  roles:
    - kubernetes/kubernetes-common
  tags: kubernetes-common
  become: yes

- hosts: k8s_masters
  roles:
    - kubernetes/kubernetes-master
    - kubernetes/kubernetes-postinstall
  tags: kubernetes-masters

- hosts: k8s_nodes
  roles:
    - kubernetes/kubernetes-nodes
  tags: kubernetes-nodes

- hosts: k8s_masters
  roles:
    - kubernetes/kubernetes-applications/flannel
    - kubernetes/kubernetes-applications/metallb
    - kubernetes/kubernetes-applications/nginx-ingress-controller
#    - kubernetes/kubernetes-applications/traefik
    - kubernetes/kubernetes-applications/cert-manager
    - kubernetes/kubernetes-applications/metric-server
#    - kubernetes/kubernetes-applications/domoticz
#    - kubernetes/kubernetes-applications/jeedom
#    - kubernetes/kubernetes-applications/jenkins
#    - kubernetes/kubernetes-applications/gitlab
#    - kubernetes/kubernetes-applications/sonarqube
  tags: kubernetes-applications
