---
# Disable SELinux
- name: Install libselinux-python latest version
  package:
    name:
      - policycoreutils
      - python3-setools
    state: latest
  become: yes
  when: inventory_hostname not in groups['pi3']

- name: disabled selinux
  selinux:
    state: disabled
  when: inventory_hostname not in groups['pi3']

- name: Add the br_netfilter module
  modprobe:
    name: br_netfilter
    state: present

- name: Enable net.bridge.bridge-nf-call-iptables in sysctl
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  ignore_errors: True

- name: Enable net.ipv4.ip_forward in sysctl
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_file: /etc/sysctl.d/ipv4-ip_forward.conf
    state: present
    reload: yes

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a

- name: Add kubernetes repository to CentOs or Fedora
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Fedora'

- name: Add the packages.cloud.google.com atp key to Debian
  apt_key:
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg"
    state: present
  when: ansible_distribution == 'Debian'

- name: Add kubernetes repository to Debian
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
  when: ansible_distribution == 'Debian'

- name: Install Kubernetes packages
  package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest
  ignore_errors: True

- name: Enabled kubelet
  systemd:
    name: kubelet
    enabled: yes
