- name: Add kubernetes repository
  when: inventory_hostname in groups['k8s_masters']
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: Install Kubernetes packages
  package:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: latest

- name: Enabled kubelet
  systemd:
    name: kubelet
    enabled: yes
