---
- name: "Install cert-manager"
  block:
    - name: Copy cert-manager file yaml
      template:
        src: cert-manager.yaml
        dest: cert-manager.yaml
    - name: Install cert-manager
      shell: |
        kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.0/cert-manager.crds.yaml;
        kubectl apply -f cert-manager.yaml;
        helm upgrade cert-manager jetstack/cert-manager --install;
    - name: Delete cert-manager file yaml
      file:
        path: cert-manager
        state: absent
  tags: cert-manager
