---
- name: "Install cert-manager"
  block:
    - name: Copy cert-manager file yaml
      template:
        src: cert-manager.yaml
        dest: cert-manager.yaml
    - name: Install cert-manager
      shell: |
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.19.0-rc.2/bin/$(uname | tr '[:upper:]' '[:lower:]')/amd64/kubectl;
        chmod +x ./kubectl;
        ./kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v0.16.0/cert-manager.yaml;
        ./kubectl apply -f cert-manager.yaml;
    - name: Delete cert-manager file yaml
      file:
        path: cert-manager
        state: absent
  tags: cert-manager
