---
- name: "Install Nginx Ingress Controller"
  shell: |
    helm upgrade nginx-ingress ingress-nginx/ingress-nginx --install \
          --namespace kube-system \
          --set controller.service.externalTrafficPolicy=Local \
          --set controller.service.type=LoadBalancer \
          --set controller.nodeSelector."kubernetes\.io/hostname"=d630 \
          --set controller.admissionWebhooks.enabled=false
  tags: nginx-ingress-controller

