---
- name: Init Kubernetes cluster
  when: inventory_hostname in groups['k8s_masters']
  become: yes
  shell: |
    kubeadm init --service-cidr {{ service_cidr }} \
                 --kubernetes-version {{ kube_version }} \
                 --pod-network-cidr {{ pod_network_cidr }} \
                 --apiserver-advertise-address {{ master_ip }} \
                 {{ kubeadm_opts }} \
                 {{ init_opts }}
  args:
    creates: /etc/kubernetes/admin.conf
  register: init_cluster
  failed_when:
    - init_cluster.changed
    - init_cluster.stdout.find('has initialized successfully') == -1

- name: Create Kubernetes config directory
  file:
    path: ".kube/"
    state: directory
  when: inventory_hostname in groups['k8s_masters']

- name: Copy admin.conf to Home directory
  when: init_cluster is succeeded and inventory_hostname in groups['k8s_masters']
  become: yes
  copy:
    src: "{{ kubeadmin_config }}"
    dest: ".kube/config"
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: '0755'
    remote_src: true
