- name: Reset Kubernetes component
  shell: "kubeadm reset --force"
  register: reset_cluster
  become: yes

- name: Reset Kubernetes component
  shell: "iptables -F && rm -rf /etc/cni/*"
  #shell: "iptables -F"
  register: reset_cluster
  become: yes

- name: Delete flannel.1 interface
  command: ip link delete flannel.1
  become: yes
  ignore_errors: True

- name: Delete cni0 interface
  command: ip link delete cni0
  become: yes
  ignore_errors: True
