---
- name: Install Helm
  block:
    - name: Download Helm installer
      get_url:
        url: https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
        dest: ./get_helm.sh
        mode: 0755

    - name: Run Helm installer
      shell: ./get_helm.sh

    - name: Delete Helm installer
      file:
        path: get_helm.sh
        state: absent

    - name: Add Helm Repo
      block:
          - name: Add Helm repo stable
            shell: helm repo add stable https://charts.helm.sh/stable

          - name: Add Helm repo incubator
            shell: helm repo add incubator https://charts.helm.sh/incubator

          - name: Add Helm repo traefik
            shell: helm repo add traefik https://containous.github.io/traefik-helm-chart

          - name: Add Helm repo oteemocharts
            shell: helm repo add oteemocharts https://oteemo.github.io/charts

          - name: Add Helm repo jetstack
            shell: helm repo add jetstack https://charts.jetstack.io

          - name: Add Helm repo nginx
            shell: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx

    - name: Update Helm repo
      shell: helm repo update
  tags: helm
  when: inventory_hostname in groups['k8s_masters']
