- name: "Install KUI"
  block:
    - name: "Download Kui installer"
      get_url:
        url: https://raw.githubusercontent.com/IBM/kui/master/tools/install.sh
        dest: ./install.sh
        mode: 0755
    - name: "Run Kui installer"
      shell: /bin/sh ./install.sh
    - name: Delete Kui installer
      file:
        path: install.sh
        state: absent
  when: inventory_hostname in groups['k8s_masters']
