---
- name: Update all packages to the latest version
  package:
    name:
      - "*"
    state: latest
  become: yes

- name: Install Epel for centos release
  package:
    name:
      - epel-release
    state: latest
  become: yes
  when: ansible_distribution == "CentOS"

- name: Install packages
  package:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - rsync
    state: latest
  become: yes

- name: Install packages fot no-centos
  package:
    name:
      - python3-pkg-resources
    state: latest
  become: yes
  when: ansible_distribution not in "CentOS"

- name: install pip
  pip:
    name: pip
    executable: pip3
    state: latest
  become: yes
