---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /volume3/workspace/home-assistant
    server: 192.168.1.50
  persistentVolumeReclaimPolicy: Retain 

