---
# tasks file for docker
- name : Install Docker
  block:
  - name: install the docker repo for fedora <= 31
    dnf:
      name: https://download.docker.com/linux/fedora/docker-ce.repo
      state: present
    when: ansible_distribution == 'Fedora' and ansible_distribution <= 31

  - name: install the docker repo for fedora >= 32
    template:
      src: fedora/docker-ce.repo
      dest: /etc/yum.repos.d/docker-ce.repo
    when: ansible_distribution == 'Fedora' and ansible_distribution >= 32

  - name: Download docker install script
    get_url:
      url: https://get.docker.com
      dest: ./get-docker.sh
    when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Fedora'
  
  - name: Install docker shell
    shell: /bin/sh get-docker.sh
    when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Fedora'
  
  - name: Install docker package
    package:
      name:
        - "docker-ce"
        - "docker-ce-cli"
        - "containerd.io"
      state: latest
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora'
  
  - name: Remove docker install script
    file:
      path: get-docker.sh
      state: absent
    when: ansible_distribution != 'Ubuntu' and ansible_distribution != 'Fedora'
  
  - name: Adding a user to the docker group
    user:
      name: "{{ ansible_user }}"
      group: docker
      append: yes
  
  - name: Start and enable docker service
    systemd:
      name: docker
      state: started
      enabled: yes
      daemon_reload: yes
  