---
apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: karlhendrik/jenkins-arm:2.222.1
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
          ports:
            - containerPort: 8080
              protocol: TCP
              name: web
            - containerPort: 50000
              protocol: TCP
              name: slaves
          env:
            - name: TZ
              value: Europe/Paris
            - name: JENKINS_SLAVE_AGENT_PORT
              value: "50000"
          volumeMounts:
            - name: jenkins
              mountPath: "/var/jenkins_home"
      volumes:
        - name: jenkins
          persistentVolumeClaim:
            claimName: jenkins
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: slaves
      port: 50000
      protocol: TCP
      targetPort: 50000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-k8shomemade
spec:
  rules:
    - host: jenkins.jugou28.com
      http:
        paths:
          - path: /
            backend:
              serviceName: jenkins
              servicePort: 8080
  tls:
    - hosts:
        - jenkins.jugou28.com
      secretName: jenkins-cert

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /volume3/workspace/jenkins
    server: 192.168.1.50
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
